name: CipherNote
services:
  client:
    build: 
      context: ./client
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

  server:
    build: 
      context: ./server
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    environment:
      - DATABASE_URI=postgresql://yash:next@postgres:5432/cipher_note
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    restart: always 
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: yash
      POSTGRES_PASSWORD: next
      POSTGRES_DB: cipher_note
    volumes:
      - pg_data:/var/lib/postgresql/data  

volumes:
  pg_data: